<?php

namespace common\models;

use yii\db\ActiveRecord;

/**
 * This is the model class for table "calculator".
 *
 * @property int $idcalc
 * @property int $iiduser fkey::user
 * @property string $in_a 1st data
 * @property string $in_b 2nd data
 * @property string $in_c 3rd data
 * @property string $result result
 * @property int $created_at
 * @property int $updated_at
 *
 * @property User $iiduser0
 *
 * @author autogenerated by GII
 */
class DbCalculator extends ActiveRecord
{
    public static function tableName(){ return 'calculator'; }

    public function rules()
    {
        return [
            [['iiduser', 'in_a', 'in_b', 'in_c', 'result', 'created_at', 'updated_at'], 'required'],
            [['iiduser', 'created_at', 'updated_at'], 'integer'],
            [['in_a', 'in_b', 'in_c', 'result'], 'string', 'max' => 32],
            [['iiduser'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['iiduser' => 'id']],
        ];
    }

    public function attributeLabels()
    {
        return [
            'idcalc' => 'Num',
            'iiduser' => 'fkey::user',
            'in_a' => 'argA',
            'in_b' => 'argB',
            'in_c' => 'argC',
            'result' => 'Result',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * Gets query for [[Iiduser0]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getIiduser()
    {
        return $this->hasOne(User::class, ['id' => 'iiduser']);
    }
}
